# Site settings
title: Creative Theme
email: theme@viennalabs.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

url: https://art345.github.io
baseurl: /metoo-datastory/

twitter_username: volnyio
github_username:  volny

# Build settings
markdown: kramdown
