# Site settings
title: The MeToo movement : a data story
email: arthur.pere@epfl.ch
description: > # this means to ignore newlines until "baseurl:"
 This is our data story about the #MeToo movement.

url: https://art345.github.io
baseurl: /metoo-datastory/

github_username:  art345

# Build settings
markdown: kramdown
