# Site settings
title: My NICKI
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/metoo/" # the subpath of your site, e.g. /blog/
url: "https://art345.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
